=== ptroja/mrrocpp/src/application/rcsc/fsautomat.dtd
<!ELEMENT TaskDescription (State+,SubTask*,xi:include*)>
	<!ELEMENT SubTask (State+)>
	

	<!ELEMENT State ((ROBOT|SetOfRobots)?,ECPGeneratorType?,(TrajectoryFilePath,Trajectory)?,taskInit?,
							Speech?,AddArg?,Sensor?,TimeSpan?,GeneratorParameters?,Parameters?,transition+)>
		<!ATTLIST State id CDATA #REQUIRED>
		<!ATTLIST State type CDATA #REQUIRED>

	<!ELEMENT SetOfRobots (FirstSet?, SecSet?)>
	
	<!ELEMENT FirstSet (ROBOT+)>
	<!ELEMENT SecSet (ROBOT+)>

	<!ELEMENT ROBOT (#PCDATA)>
	<!ELEMENT ECPGeneratorType (#PCDATA)>
	<!ELEMENT TrajectoryFilePath (#PCDATA)>
	<!ELEMENT Trajectory (Pose+)>
		<!ATTLIST Trajectory coordinateType CDATA #REQUIRED>
		<!ATTLIST Trajectory numOfPoses CDATA #REQUIRED>
		
	<!ELEMENT Pose (StartVelocity,EndVelocity,Velocity,Accelerations,Coordinates)>
		<!ELEMENT StartVelocity (#PCDATA)>
		<!ELEMENT EndVelocity (#PCDATA)>
		<!ELEMENT Velocity (#PCDATA)>
		<!ELEMENT Accelerations (#PCDATA)>
		<!ELEMENT Coordinates (#PCDATA)>
	
	<!ELEMENT taskInit (ecp+,mp?)>
	<!ELEMENT ecp (ecp_gen_t?,ecp_tool_change_gen?,ecp_tff_nose_run_gen?,ecp_tff_rubik_grab_gen?,
		ecp_tff_gripper_approach_gen?,ecp_tff_rubik_face_rotate_gen?,ecp_teach_in_gen?,
		bias_edp_force_gen?,ecp_smooth_gen?,weight_meassure_gen?,ecp_sub_task_gripper_opening?)>
		<!ATTLIST ecp name CDATA #REQUIRED>
		<!ELEMENT ecp_gen_t (#PCDATA)>
		<!ELEMENT ecp_tool_change_gen (#PCDATA)>
		<!ELEMENT ecp_tff_nose_run_gen (#PCDATA)>
		<!ELEMENT ecp_tff_rubik_grab_gen (#PCDATA)>
		<!ELEMENT ecp_tff_gripper_approach_gen (#PCDATA)>
		<!ELEMENT ecp_tff_rubik_face_rotate_gen (#PCDATA)>
		<!ELEMENT ecp_teach_in_gen (#PCDATA)>
		<!ELEMENT bias_edp_force_gen (#PCDATA)>
		<!ELEMENT ecp_smooth_gen (#PCDATA)>
		<!ELEMENT weight_meassure_gen (#PCDATA)>
		<!ELEMENT ecp_sub_task_gripper_opening (#PCDATA)>
	
	<!ELEMENT mp (cube_state?,Sensor*,Transmitter?)>
		<!ELEMENT cube_state (#PCDATA)>
		<!ELEMENT Transmitter (#PCDATA)>
	
	<!ELEMENT Speech (#PCDATA)>
	<!ELEMENT AddArg (#PCDATA)>
	<!ELEMENT Sensor (#PCDATA)>
	<!ELEMENT TimeSpan (#PCDATA)>
	<!ELEMENT GeneratorParameters (#PCDATA)>
	<!ELEMENT Parameters (#PCDATA)>

	<!ELEMENT transition (#PCDATA)>
		<!ATTLIST transition condition CDATA #REQUIRED>
		<!ATTLIST transition target CDATA #REQUIRED>

	<!ELEMENT xi:include (xi:fallback?)>	
	<!ATTLIST xi:include
		xmlns:xi        CDATA       #FIXED    "http://www.w3.org/2001/XInclude"
		href            CDATA       #IMPLIED
		parse           (xml|text)  "xml"
		xpointer        CDATA       #IMPLIED
		encoding        CDATA       #IMPLIED
		accept          CDATA       #IMPLIED
		accept-language CDATA       #IMPLIED
	>
	
	<!ELEMENT xi:fallback ANY>
	<!ATTLIST xi:fallback
        xmlns:xi   CDATA   #FIXED   "http://www.w3.org/2001/XInclude"
    >

=== ptroja/mrrocpp/src/application/rcsc/XMLfiles/asia2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE TaskDescription SYSTEM "fsautomat.dtd" >

<TaskDescription>
<State id="INIT" type="systemInitialization" xpos="11" ypos="22">
		<taskInit>
			<ecp name="ROBOT_IRP6_ON_TRACK">
				<ecp_gen_t></ecp_gen_t>
				<ecp_smooth_gen>10</ecp_smooth_gen>
				<ecp_sub_task_gripper_opening>10</ecp_sub_task_gripper_opening>		
			</ecp>
			<ecp name="ROBOT_IRP6_POSTUMENT">
				<ecp_gen_t></ecp_gen_t>
				<ecp_smooth_gen>10</ecp_smooth_gen>
				<ecp_sub_task_gripper_opening>10</ecp_sub_task_gripper_opening>		
			</ecp>
		</taskInit>
		<transition condition="true" target="stan1"/>
	</State>	
	
	
		
	<State id="rcTaskInit" type="configureAllSensors"  xpos="11" ypos="22">
		<AddArg>1</AddArg>
		<transition condition="true" target="stan1"/>
	</State>


	
	
	<State id= "stan1" type="runGenerator" xpos="11" ypos="22">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>src/application/rcsc/trj/irp6ot_sm_ap_1.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<Velocity>0	0	0	0	0	0	0	0</Velocity>
				<Accelerations>0	0	0	0	0	0	0	0</Accelerations>
				<Coordinates>0	0	0	0	0	0	0	0</Coordinates>
 			</Pose>
		</Trajectory>
		<transition condition="true" target="stan2"/>
	</State>
	
	
	
	<State id="stan2" type="runGenerator" xpos="11" ypos="22">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>src/application/rcsc/trj/irp6ot_sm_ap_1.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
			<Velocity>0	0	0	0	0	0	0	0</Velocity>
			<Accelerations>0	0	0	0	0	0	0	0</Accelerations>
			<Coordinates>0	0	0	0	0	0	0	0</Coordinates>
 			</Pose>
		</Trajectory>
		<transition condition="true" target="stan3"/>
	</State>
	
	
	<State id="stan3" type="emptyGenForSet" xpos="11" ypos="22">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="stan4"/>
	</State>

	
	
	<State id="stan4" type="emptyGen" xpos="11" ypos="22">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
		<AddArg>1</AddArg>
		<transition condition="true" target="stan5"/>
	</State>
	
	
	
	
	<State id="stan5" type="stopGen" xpos="11" ypos="22">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</FirstSet>			
		</SetOfRobots>
		<transition condition="true" target="_STOP_"/>
	</State>
	
</TaskDescription>

=== ptroja/mrrocpp/src/application/askubis_swarm_demo/rcsc.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE TaskDescription SYSTEM "fsautomat.dtd" >

<TaskDescription>
	<State id="INIT" type="systemInitialization">
		<taskInit>
			<ecp name="ROBOT_IRP6_ON_TRACK">
				<ecp_smooth_gen>1</ecp_smooth_gen>		
			</ecp>
			<ecp name="ROBOT_IRP6_POSTUMENT">
				<ecp_smooth_gen>1</ecp_smooth_gen>
			</ecp>
		</taskInit>
		<transition condition="true" target="approach_12"/>
	</State>	
	<State id="approach_12" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	0.5	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.01</Accelerations>
				<Coordinates>0	-0.087462	-1.54187	0.024063	1.21873	2.57816	-2.66439	0.057</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="approach_13"/>
	</State>
	<State id="approach_13" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	0.5	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.01</Accelerations>
				<Coordinates>-0.100633	-1.54194	0.048591	1.19773	2.10098	-2.7312	0.074	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="_END_"/>
	</State>
	
	<!-- ################################################################################################################################### -->

	<xi:include href="faceTurnOperations.xml" parse="xml" xmlns:xi='http://www.w3.org/2001/XInclude'/>
	<xi:include href="faceChangeOperations.xml" parse="xml" xmlns:xi='http://www.w3.org/2001/XInclude'/>
	<!-- ################################################################################################################################### -->
	<!--  -->
	<!--  -->
	
</TaskDescription>

=== ptroja/mrrocpp/src/application/rcsc/rcsc.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE TaskDescription SYSTEM "fsautomat.dtd" >

<TaskDescription>
	<State id="INIT" type="systemInitialization">
		<taskInit>
			<ecp name="ROBOT_IRP6P_M">
				<ecp_smooth_gen>6</ecp_smooth_gen>
				<bias_edp_force_st></bias_edp_force_st>
			</ecp>
			<ecp name="ROBOT_IRP6OT_M">
				<ecp_smooth_gen>7</ecp_smooth_gen>
				<bias_edp_force_st></bias_edp_force_st>
			</ecp>
		</taskInit>
		<transition condition="true" target="approach_1"/>
	</State>
	<State id="approach_1" type="runGenerator">
		<ROBOT>ROBOT_IRP6P_M</ROBOT>
		<ECPGeneratorType>ECP_GEN_NEWSMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>../../src/application/swarm_demo/trajectory_postument_joint.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<Velocity>0.1	0.1	0.1	0.1	0.1	0.1</Velocity>
				<Accelerations>0.07	0.07	0.07	0.07	0.07	0.07</Accelerations>
				<Coordinates>-1.576715 -1.910680 0.299621 0.039053 1.570008 -1.563285</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="approach_2"/>
	</State>
	<State id="approach_2" type="runGenerator">
		<ROBOT>ROBOT_IRP6OT_M</ROBOT>
		<ECPGeneratorType>ECP_GEN_NEWSMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>../../src/application/swarm_demo/trajectory_track_joint.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<Velocity>0.05	0.2	0.2	0.2	0.2	0.2	0.2</Velocity>
				<Accelerations>0.04	0.08	0.08	0.08	0.08	0.08	0.08</Accelerations>
				<Coordinates>0.20000 1.570545 -1.760752 0.202086 0.011934 1.570013 1.570545</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="approach_3"/>
	</State>
	<State id="approach_3" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6P_M</ROBOT>
				<ROBOT>ROBOT_IRP6OT_M</ROBOT>
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6P_M</ROBOT>
				<ROBOT>ROBOT_IRP6OT_M</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="bias_post"/>
	</State>
	<State id="bias_post" type="runGenerator">
		<ROBOT>ROBOT_IRP6P_M</ROBOT>
		<ECPGeneratorType>ECP_ST_BIAS_EDP_FORCE</ECPGeneratorType>
		<AddArg>5</AddArg>
		<transition condition="true" target="bias_track"/>
	</State>
	<State id="bias_track" type="runGenerator">
		<ROBOT>ROBOT_IRP6OT_M</ROBOT>
		<ECPGeneratorType>ECP_ST_BIAS_EDP_FORCE</ECPGeneratorType>
		<AddArg>5</AddArg>
		<transition condition="true" target="wait2"/>
	</State>
	<State id="wait2" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6P_M</ROBOT>
				<ROBOT>ROBOT_IRP6OT_M</ROBOT>
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6P_M</ROBOT>
				<ROBOT>ROBOT_IRP6OT_M</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="approach_4"/>
	</State>
	<State id="approach_4" type="wait">
		<TimeSpan>1000</TimeSpan>
		<transition condition="true" target="approach_5"/>
	</State>
	<State id="approach_5" type="runGenerator">
		<ROBOT>ROBOT_IRP6P_M</ROBOT>
		<ECPGeneratorType>ECP_GEN_NEWSMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>../../src/application/swarm_demo/trajectory_postument_angle_p1.trj</TrajectoryFilePath>
		<Trajectory coordinateType="ecp_XYZ_ANGLE_AXIS" numOfPoses="1">
			<Pose>
				<Velocity>0.1	0.1	0.1	0.1	0.1	0.1</Velocity>
				<Accelerations>0.07	0.07	0.07	0.07	0.07	0.07</Accelerations>
				<Coordinates> -0.509557 1.268231 0.676142  0 0 1.57</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="approach_6"/>
	</State>
	<State id="approach_6" type="emptyGen">
		<ROBOT>ROBOT_IRP6OT_M</ROBOT>	
		<AddArg>1</AddArg>
		<transition condition="true" target="post_grip_1"/>
	</State>
	<State id="post_grip_1" type="runGenerator">
		<ROBOT>ROBOT_IRP6P_M</ROBOT>
		<ECPGeneratorType>ECP_GEN_TFF_GRIPPER_APPROACH</ECPGeneratorType>
		<AddArg>0</AddArg>
		<transition condition="true" target="wait_post"/>
	</State>
	<State id="wait_post" type="emptyGen">
		<ROBOT>ROBOT_IRP6OT_M</ROBOT>	
		<AddArg>1</AddArg>
		<transition condition="true" target="wait_"/>
	</State>
	<State id="wait_" type="wait">
		<TimeSpan>1000</TimeSpan>
		<transition condition="true" target="_STOP_"/>
	</State>
	
	<!-- ################################################################################################################################### -->

	<!-- <xi:include href="faceTurnOperations.xml" parse="xml" xmlns:xi='http://www.w3.org/2001/XInclude'/> -->
	<!-- <xi:include href="faceChangeOperations.xml" parse="xml" xmlns:xi='http://www.w3.org/2001/XInclude'/> -->
	<!-- ################################################################################################################################### -->
	<!--  -->
	<!--  -->
	
</TaskDescription>
