<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TaskDescription [
	<!ELEMENT TaskDescription (State+)>

	<!ELEMENT State ((ROBOT|SetOfRobots)?,ECPGeneratorType?,TrajectoryFilePath?,Trajectory?,taskInit?,
							Speech?,AddArg?,Sensor?,TimeSpan?,GeneratorParameters?,Parameters?,transition+)>
		<!ATTLIST State id CDATA #REQUIRED>
		<!ATTLIST State type CDATA #REQUIRED>

	<!ELEMENT SetOfRobots (FirstSet?, SecSet?)>
	
	<!ELEMENT FirstSet (ROBOT+)>
	<!ELEMENT SecSet (ROBOT+)>

	<!ELEMENT ROBOT (#PCDATA)>
	<!ELEMENT ECPGeneratorType (#PCDATA)>
	<!ELEMENT TrajectoryFilePath (#PCDATA)>
	<!ELEMENT Trajectory (Pose+)>
		<!ATTLIST Trajectory coordinateType CDATA #REQUIRED>
		<!ATTLIST Trajectory numOfPoses CDATA #REQUIRED>
		
	<!ELEMENT Pose (StartVelocity,EndVelocity,Velocity,Accelerations,Coordinates)>
		<!ELEMENT StartVelocity (#PCDATA)>
		<!ELEMENT EndVelocity (#PCDATA)>
		<!ELEMENT Velocity (#PCDATA)>
		<!ELEMENT Accelerations (#PCDATA)>
		<!ELEMENT Coordinates (#PCDATA)>
	
	<!ELEMENT taskInit (ecp+,mp?)>
	<!ELEMENT ecp (ecp_gen_t?,ecp_tool_change_gen?,ecp_tff_nose_run_gen?,ecp_tff_rubik_grab_gen?,
		ecp_tff_gripper_approach_gen?,ecp_tff_rubik_face_rotate_gen?,ecp_teach_in_gen?,
		bias_edp_force_gen?,ecp_smooth_gen?,weight_meassure_gen?,ecp_sub_task_gripper_opening?)>
		<!ATTLIST ecp name CDATA #REQUIRED>
		<!ELEMENT ecp_gen_t (#PCDATA)>
		<!ELEMENT ecp_tool_change_gen (#PCDATA)>
		<!ELEMENT ecp_tff_nose_run_gen (#PCDATA)>
		<!ELEMENT ecp_tff_rubik_grab_gen (#PCDATA)>
		<!ELEMENT ecp_tff_gripper_approach_gen (#PCDATA)>
		<!ELEMENT ecp_tff_rubik_face_rotate_gen (#PCDATA)>
		<!ELEMENT ecp_teach_in_gen (#PCDATA)>
		<!ELEMENT bias_edp_force_gen (#PCDATA)>
		<!ELEMENT ecp_smooth_gen (#PCDATA)>
		<!ELEMENT weight_meassure_gen (#PCDATA)>
		<!ELEMENT ecp_sub_task_gripper_opening (#PCDATA)>
	
	<!ELEMENT mp (cube_state?,Sensor*,Transmitter?)>
		<!ELEMENT cube_state (#PCDATA)>
		<!ELEMENT Transmitter (#PCDATA)>
	
	<!ELEMENT Speech (#PCDATA)>
	<!ELEMENT AddArg (#PCDATA)>
	<!ELEMENT Sensor (#PCDATA)>
	<!ELEMENT TimeSpan (#PCDATA)>
	<!ELEMENT GeneratorParameters (#PCDATA)>
	<!ELEMENT Parameters (#PCDATA)>

	<!ELEMENT transition (#PCDATA)>
		<!ATTLIST transition condition CDATA #REQUIRED>
		<!ATTLIST transition target CDATA #REQUIRED>

]>

<TaskDescription>
	<State id="INIT" type="systemInitialization">
		<taskInit>
			<ecp name="ROBOT_IRP6_ON_TRACK">
				<ecp_gen_t></ecp_gen_t>
				<ecp_tff_nose_run_gen>8</ecp_tff_nose_run_gen>
				<ecp_tff_rubik_grab_gen>8</ecp_tff_rubik_grab_gen>
				<ecp_tff_gripper_approach_gen>8</ecp_tff_gripper_approach_gen>
				<ecp_tff_rubik_face_rotate_gen>8</ecp_tff_rubik_face_rotate_gen>
				<ecp_teach_in_gen></ecp_teach_in_gen>
				<bias_edp_force_gen></bias_edp_force_gen>
				<ecp_smooth_gen>1</ecp_smooth_gen>
				<weight_meassure_gen>1</weight_meassure_gen>
				<ecp_sub_task_gripper_opening></ecp_sub_task_gripper_opening>		
			</ecp>
			<ecp name="ROBOT_IRP6_POSTUMENT">
				<ecp_gen_t></ecp_gen_t>
				<ecp_tff_nose_run_gen>8</ecp_tff_nose_run_gen>
				<ecp_tff_rubik_grab_gen>8</ecp_tff_rubik_grab_gen>
				<ecp_tff_gripper_approach_gen>8</ecp_tff_gripper_approach_gen>
				<ecp_tff_rubik_face_rotate_gen>8</ecp_tff_rubik_face_rotate_gen>
				<ecp_teach_in_gen></ecp_teach_in_gen>
				<bias_edp_force_gen></bias_edp_force_gen>
				<ecp_smooth_gen>1</ecp_smooth_gen>
				<ecp_sub_task_gripper_opening></ecp_sub_task_gripper_opening>		
			</ecp>
			<ecp name="FESTIVAL">
				<!--
				<festival_gen></festival_gen>
				-->
			</ecp>
			<mp>
				<cube_state></cube_state>
				<Sensor>SENSOR_CAMERA_ON_TRACK</Sensor>
				<Sensor>SENSOR_CAMERA_SA</Sensor>
				<Transmitter>TRANSMITTER_RC_WINDOWS</Transmitter>
			</mp>
		</taskInit>
		<transition condition="true" target="approach_1"/>
	</State>
	<!-- proba zapisania inicjalizacji elementow potrzebnych do wykonania zadania ukladania kostki (pomijam inicjalizaje na poziome ECP)  -->
	<!-- configure_edp_force_sensor(true, true) -->
	<!-- ########################################## APPROACH_OP ######################################################################## -->
	<!--
	<State id="rcTaskInit" type="configureAllSensors">
		<AddArg>1</AddArg>
		<transition condition="true" target="approach_1"/>
	</State>
	-->
	<State id="approach_1" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_BIAS_EDP_FORCE</ECPGeneratorType>
		<transition condition="true" target="approach_2"/>
	</State>
	<State id="approach_2" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_BIAS_EDP_FORCE</ECPGeneratorType>
		<transition condition="true" target="approach_3"/>
	</State>
	<State id="approach_3" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="approach_4"/>
	</State>

	<!-- uruchomienie festivala, czyli wlaczenie generatora mowy  -->
	<State id="approach_4" type="runGenerator">
		<ROBOT>ROBOT_FESTIVAL</ROBOT>
		<ECPGeneratorType>ECP_GEN_TRANSPARENT</ECPGeneratorType>
		<Speech>jestem podatny</Speech>
		<AddArg>1</AddArg>
		<transition condition="true" target="approach_5"/>
	</State>
	<State id="approach_5" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="iniFile.irp6p_compliant" target="approach_6"/>
		<transition condition="true" target="approach_9"/>
	</State>

	<!-- sprawdzenie warunku z pliku konfiguracyjnego i wejscie w zbior stanow -->
	<!-- dla POSTUMENT -->
	<State id="approach_6" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_TFF_NOSE_RUN</ECPGeneratorType>
		<transition condition="true" target="approach_7"/>
	</State>
	<State id="approach_7" type="emptyGen">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
		<AddArg>1</AddArg>
		<transition condition="true" target="approach_8"/>
	</State>
	<State id="approach_8" type="stopGen">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</FirstSet>			
		</SetOfRobots>
		<transition condition="true" target="approach_12"/>
	</State>
	<!-- dla ON_TRACK'a -->
	<State id="approach_9" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_TFF_NOSE_RUN</ECPGeneratorType>
		<transition condition="true" target="approach_10"/>
	</State>
	<State id="approach_10" type="emptyGen">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>		
		<AddArg>1</AddArg>
		<transition condition="true" target="approach_11"/>
	</State>
	<State id="approach_11" type="stopGen">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>			
			</FirstSet>			
		</SetOfRobots>
		<transition condition="true" target="approach_12"/>
	</State>
	<!-- wykonanie ruchu -->	
	<State id="approach_12" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/rcsc/irp6ot_sm_ap_1.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<StartVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</StartVelocity>
				<EndVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	0.5	1.0</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.01</Accelerations>
				<Coordinates>0.000000 -0.087462 -1.541873 0.024063 1.218727 2.578164 -2.664387 0.059000</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="approach_13"/>
	</State>
	<State id="approach_13" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/rcsc/irp6p_sm_ap_1.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<StartVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0</StartVelocity>
				<EndVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	0.5	1.0</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.01</Accelerations>
				<Coordinates>-0.100633 -1.541943 0.048591 1.197734 2.100977 -2.731195 0.074000 0.0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="approach_14"/>
	</State>
	<State id="approach_14" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="approach_15"/>
	</State>
	<!-- uruchomienie festivala, czyli wlaczenie generatora mowy i ON_TRACK'a -->
	<State id="approach_15" type="runGenerator">
		<ROBOT>ROBOT_FESTIVAL</ROBOT>
		<ECPGeneratorType>ECP_GEN_TRANSPARENT</ECPGeneratorType>
		<Speech>jestem robotem usl/ugowym</Speech>
		<transition condition="true" target="approach_16"/>
	</State>
	<State id="approach_16" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/rcsc/irp6ot_sm_ap_2.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<StartVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</StartVelocity>
				<EndVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	0.5	1.0</Velocity>
				<Accelerations>0.3	0.3	0.3	0.3	0.3	0.3	0.3	1.0</Accelerations>
				<Coordinates>0.000000 -0.000056 -1.570689 0.000365 1.559536 1.570215 -2.320805 0.088</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="approach_17"/>
	</State>
	<State id="approach_17" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="approach_18"/>
	</State>

	<!-- uruchomienie festivala, czyli wlaczenie generatora mowy -->
	<State id="approach_18" type="runGenerator">
		<ROBOT>ROBOT_FESTIVAL</ROBOT>
		<ECPGeneratorType>ECP_GEN_TRANSPARENT</ECPGeneratorType>
		<Speech>ul/oz*e~ kostke~ rubika</Speech>
		<transition condition="true" target="approach_19"/>
	</State>
	<State id="approach_19" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="approach_20"/>
	</State>

	<!-- uruchomienie festivala, czyli wlaczenie generatora mowy -->
	<State id="approach_20" type="runGenerator">
		<ROBOT>ROBOT_FESTIVAL</ROBOT>
		<ECPGeneratorType>ECP_GEN_TRANSPARENT</ECPGeneratorType>
		<Speech>podaj kostke~</Speech>
		<transition condition="true" target="approach_21"/>
	</State>
	<State id="approach_21" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="approach_22"/>
	</State>

	<!-- wlaczenie generatora transparentnego -->	
	<State id="approach_22" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_TRANSPARENT</ECPGeneratorType>
		<transition condition="true" target="approach_23"/>
	</State>
	<State id="approach_23" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_TRANSPARENT</ECPGeneratorType>
		<transition condition="true" target="approach_26"/>
	</State>
	<!--
	<State id="approach_24" type="emptyGenForSet">
		<ROBOT>ROBOT_IRP6_ON_TRACK;ROBOT_IRP6_POSTUMENT;ROBOT_FESTIVAL</ROBOT>		
	</State>
	-->
	
	<!-- sprawdzenie warunku dla wlaczenia serwa wizyjnego i wlaczenie go -->	
	<!--
	<State id="approach_25" type="eyeGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<AddArg>4</AddArg>
		<Sensor>SENSOR_CAMERA_SA</Sensor>
	</State>
	-->
	<!-- zatrzymanie generatora dla robotow -->
	<State id="approach_26" type="stopGen">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</FirstSet>			
		</SetOfRobots>
		<transition condition="true" target="approach_27"/>
	</State>
	
	<!-- czekanie wsazana liczbe milisekund -->
	<State id="approach_27" type="wait">
		<TimeSpan>500</TimeSpan>
		<transition condition="true" target="approach_28"/>
	</State>
	
	<!-- zacisniecie chwytaka na kostce  -->
	<State id="approach_28" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_TFF_RUBIK_GRAB</ECPGeneratorType>
		<GeneratorParameters>0.057	0.00005	0</GeneratorParameters>
		<transition condition="true" target="approach_29"/>
	</State>
	<State id="approach_29" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="approach_30"/>
	</State>
	<State id="approach_30" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_TFF_RUBIK_GRAB</ECPGeneratorType>
		<GeneratorParameters>0.057	0.00005	50</GeneratorParameters>
		<transition condition="true" target="approach_31"/>
	</State>
	<State id="approach_31" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="approach_32"/>
	</State>

	<!-- uruchomienie festivala, czyli wlaczenie generatora mowy -->
	<State id="approach_32" type="runGenerator">
		<ROBOT>ROBOT_FESTIVAL</ROBOT>
		<ECPGeneratorType>ECP_GEN_TRANSPARENT</ECPGeneratorType>
		<Speech>pus~c~ kostke~</Speech>
		<transition condition="true" target="approach_33"/>
	</State>
	<State id="approach_33" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="approach_34"/>
	</State>
	<State id="approach_34" type="wait">
		<TimeSpan>1000</TimeSpan>
		<transition condition="true" target="approach_35"/>
	</State>
	
	<!-- wykonanie ruchu -->	
	<State id="approach_35" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/rcsc/irp6ot_sm_ap_3.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="4">
			<Pose>
				<StartVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</StartVelocity>
				<EndVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	0.5	1.0</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.01</Accelerations>
				<Coordinates>0.000000 0.618665 -1.805564 0.094866 0.109006 1.526905 -2.077055 0.057</Coordinates>
			</Pose>
			<Pose>
				<StartVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</StartVelocity>
				<EndVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	0.5	1.0</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.01</Accelerations>
				<Coordinates>0.000000 0.618665 -1.805564 0.094866 0.109006 1.526905 -2.077055 0.062</Coordinates>
			</Pose>
			<Pose>
				<StartVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</StartVelocity>
				<EndVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	0.5	1.0</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.01</Accelerations>
				<Coordinates>0.000000 0.618665 -1.805564 0.094866 0.109006 1.526905 -2.077055 0.057</Coordinates>
			</Pose>
			<Pose>
				<StartVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</StartVelocity>
				<EndVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	0.5	1.0</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.01</Accelerations>
				<Coordinates>0.160123 1.811557 -1.571591 0.185117 0.573102 2.502174 0.518841 0.057</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="approach_36"/>
	</State>
	<State id="approach_36" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="identify_colors_1"/>
		<transition condition="false" target="STOP"/>
	</State>
	
	<!-- ########################################## IDENTIFY_COLORS ######################################################################## -->
	<State id="identify_colors_1" type="cubeStateInit">
		<Parameters>BLUE	GREEN	RED	ORANGE	WHITE	YELLOW</Parameters>
		<transition condition="true" target="ica_1>>identify_colors_2"/>
		<transition condition="true" target="STOP"/>
	</State>
	<State id="identify_colors_2" type="cubeStateWriting">
		<AddArg>0</AddArg>
		<Sensor>SENSOR_CAMERA_ON_TRACK</Sensor>
		<transition condition="true" target="identify_colors_3"/>
	</State>
	<State id="identify_colors_3" type="wait">
		<TimeSpan>1000</TimeSpan>
		<transition condition="true" target="fco_CL_0_1>>identify_colors_4"/>
	</State>

	<State id="identify_colors_4" type="intermediateState">
		<transition condition="true" target="ica_1>>identify_colors_5"/>
	</State>
	<State id="identify_colors_5" type="cubeStateWriting">
		<AddArg>1</AddArg>
		<Sensor>SENSOR_CAMERA_ON_TRACK</Sensor>
		<transition condition="true" target="identify_colors_6"/>
	</State>
	<State id="identify_colors_6" type="wait">
		<TimeSpan>1000</TimeSpan>
		<transition condition="true" target="fco_CL_0_1>>identify_colors_7"/>
	</State>

	<State id="identify_colors_7" type="intermediateState">
		<transition condition="true" target="ica_1>>identify_colors_8"/>
	</State>
	<State id="identify_colors_8" type="cubeStateWriting">
		<AddArg>2</AddArg>
		<Sensor>SENSOR_CAMERA_ON_TRACK</Sensor>
		<transition condition="true" target="identify_colors_9"/>
	</State>
	<State id="identify_colors_9" type="wait">
		<TimeSpan>1000</TimeSpan>
		<transition condition="true" target="fco_CL_180_1>>identify_colors_10"/>
	</State>

	<State id="identify_colors_10" type="intermediateState">
		<transition condition="true" target="ica_1>>identify_colors_11"/>
	</State>
	<State id="identify_colors_11" type="cubeStateWriting">
		<AddArg>3</AddArg>
		<Sensor>SENSOR_CAMERA_ON_TRACK</Sensor>
		<transition condition="true" target="identify_colors_12"/>
	</State>
	<State id="identify_colors_12" type="wait">
		<TimeSpan>1000</TimeSpan>
		<transition condition="true" target="fco_CL_0_1>>identify_colors_13"/>
	</State>

	<State id="identify_colors_13" type="intermediateState">
		<transition condition="true" target="ica_1>>identify_colors_14"/>
	</State>
	<State id="identify_colors_14" type="cubeStateWriting">
		<AddArg>4</AddArg>
		<Sensor>SENSOR_CAMERA_ON_TRACK</Sensor>
		<transition condition="true" target="identify_colors_15"/>
	</State>
	<State id="identify_colors_15" type="wait">
		<TimeSpan>1000</TimeSpan>
		<transition condition="true" target="fco_CL_180_1>>identify_colors_16"/>
	</State>

	<State id="identify_colors_16" type="intermediateState">
		<transition condition="true" target="ica_1>>identify_colors_17"/>
	</State>
	<State id="identify_colors_17" type="cubeStateWriting">
		<AddArg>5</AddArg>
		<Sensor>SENSOR_CAMERA_ON_TRACK</Sensor>
		<transition condition="true" target="identify_colors_18"/>
	</State>
	<State id="identify_colors_18" type="wait">
		<TimeSpan>1000</TimeSpan>
		<transition condition="true" target="fco_CL_0_1>>communicate_wws_1"/>
	</State>
	
	<!-- ################################################################################################################################### -->
	<!-- identify colors main algorithm -->
	<State id="ica_1" type="intermediateState">
		<transition condition="true" target="fto_CL_0_1>>ica_2"/>
	</State>
	<State id="ica_2" type="runGenerator">
		<ROBOT>ROBOT_FESTIVAL</ROBOT>
		<ECPGeneratorType>ECP_GEN_TRANSPARENT</ECPGeneratorType>
		<Speech>oglo~dam kolory na s~ciance</Speech>
		<transition condition="true" target="ica_3"/>
	</State>
	<State id="ica_3" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="ica_4"/>
	</State>
	<State id="ica_4" type="wait">
		<TimeSpan>5000</TimeSpan>
		<transition condition="true" target="ica_5"/>
	</State>
	<State id="ica_5" type="initiateSensorReading">
		<Sensor>SENSOR_CAMERA_ON_TRACK</Sensor>
		<transition condition="true" target="ica_6"/>
	</State>
	<State id="ica_6" type="wait">
		<TimeSpan>1000</TimeSpan>
		<transition condition="true" target="ica_7"/>
	</State>
	<State id="ica_7" type="getSensorReading">
		<Sensor>SENSOR_CAMERA_ON_TRACK</Sensor>
		<transition condition="true" target="_END_"/>
	</State>
	
	<!-- ################################################################################################################################### -->
		
	<!--  -->

	
	<!-- ########################################## FACE_TURN_OP ########################################################################### -->
	<State id="fto_CL_90_1" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/rcsc/irp6ot_sm_fturn_ap_cl_90_phase_1.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<StartVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</StartVelocity>
				<EndVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	0.5	1.0</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.01</Accelerations>
				<Coordinates>0.160123 1.811557 -1.571591 0.185117 0.573102 2.502174 -1.050994 0.057</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="fto_CL_90_2"/>
	</State>
	<State id="fto_CL_90_2" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/rcsc/irp6p_sm_fturn_ap_cl_90_phase_1.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<StartVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0</StartVelocity>
				<EndVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	1.0	0.0</Velocity>
				<Accelerations>0.2	0.2	0.2	0.2	0.2	0.2	0.01	0.0</Accelerations>
				<Coordinates>-1.296823 -1.526247 -0.027612 -0.513367 3.769948 -0.449990 0.085000 0.0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="fto_CL_90_3"/>
	</State>
	<State id="fto_CL_90_3" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="fto_CL_90_4"/>
	</State>
	<State id="fto_CL_90_4" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/rcsc/irp6ot_sm_fturn_ap_cl_90_phase_2.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="2">
			<Pose>
				<StartVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</StartVelocity>
				<EndVelocity>0.0	0.0	0.01	0.01	0.0	0.0	0.0	0.0</EndVelocity>
				<Velocity>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.5</Velocity>
				<Accelerations>0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.01</Accelerations>
				<Coordinates>0.160141 1.74328 -1.51174 0.13169 0.602759 2.40249 -0.995512 0.057</Coordinates>
			</Pose>
			<Pose>
				<StartVelocity>0.0	0.0	0.01	0.01	0.0	0.0	0.0	0.0	</StartVelocity>
				<EndVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</EndVelocity>
				<Velocity>0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.05</Velocity>
				<Accelerations>0.002	0.002	0.002	0.002	0.002	0.002	0.002	0.001</Accelerations>
				<Coordinates>0.160123 1.716892 -1.487739 0.109636 0.615859 2.364 -0.973001 0.057</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="fto_CL_90_5"/>
	</State>
	<State id="fto_CL_90_5" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="fto_CL_90_6"/>
	</State>
	<State id="fto_CL_90_6" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_BIAS_EDP_FORCE</ECPGeneratorType>
		<transition condition="true" target="fto_CL_90_7"/>
	</State>
	<State id="fto_CL_90_7" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_BIAS_EDP_FORCE</ECPGeneratorType>
		<transition condition="true" target="fto_CL_90_8"/>
	</State>
	<State id="fto_CL_90_8" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="fto_CL_90_9"/>
	</State>
	<State id="fto_CL_90_9" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_TFF_RUBIK_GRAB</ECPGeneratorType>
		<GeneratorParameters>0.057	0.00005	0</GeneratorParameters>
		<transition condition="true" target="fto_CL_90_10"/>
	</State>
	<State id="fto_CL_90_10" type="emptyGen">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
		<AddArg>0</AddArg>
		<transition condition="true" target="fto_CL_90_11"/>
	</State>
	<State id="fto_CL_90_11" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_TFF_RUBIK_GRAB</ECPGeneratorType>
		<GeneratorParameters>0.057	0.00005	50</GeneratorParameters>
		<transition condition="true" target="fto_CL_90_12"/>
	</State>
	<State id="fto_CL_90_12" type="emptyGen">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
		<AddArg>0</AddArg>
		<transition condition="true" target="fto_CL_90_13"/>
	</State>
	<State id="fto_CL_90_13" type="runGenerator">
		<ROBOT>ROBOT_FESTIVAL</ROBOT>
		<ECPGeneratorType>ECP_GEN_TRANSPARENT</ECPGeneratorType>
		<Speech>obracam kostke~</Speech>
		<transition condition="true" target="fto_CL_90_14"/>
	</State>
	<State id="fto_CL_90_14" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_TFF_RUBIK_FACE_ROTATE</ECPGeneratorType>
		<GeneratorParameters>90.0</GeneratorParameters>
		<transition condition="true" target="fto_CL_90_15"/>
	</State>
	<State id="fto_CL_90_15" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_FESTIVAL</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="fto_CL_90_16"/>
	</State>
	<State id="fto_CL_90_16" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>RCSC_GRIPPER_OPENING</ECPGeneratorType>
		<GeneratorParameters>0.02	1000</GeneratorParameters>
		<transition condition="true" target="fto_CL_90_17"/>
	</State>
	<State id="fto_CL_90_17" type="emptyGen">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>		
		<AddArg>0</AddArg>
		<transition condition="true" target="fto_CL_90_18"/>
	</State>
	<State id="fto_CL_90_18" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/rcsc/irp6ot_sm_fturn_de.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<StartVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</StartVelocity>
				<EndVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	0.5	1.0</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.01</Accelerations>
				<Coordinates>0.160117 1.811383 -1.556191 0.198112 0.560941 2.452480 0.500680 0.085032</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="fto_CL_90_19"/>
	</State>
	<State id="fto_CL_90_19" type="emptyGen">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>		
		<AddArg>0</AddArg>
		<transition condition="true" target="_END_"/>
	</State>
	<!-- ################################################################################################################################### -->
	
	<!-- ################################################################################################################################### -->
	<!-- FOR CL_0 ARGUMENT -->
	<State id="fto_CL_0_1" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/rcsc/irp6ot_sm_fturn_ap_cl_0_phase_1.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<StartVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</StartVelocity>
				<EndVelocity>0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	0.5	1.0</Velocity>